sever:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: mqtt-bot
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mqtt-bot
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api-docs
