# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mqtt-bot-fe/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mqtt-bot-fe/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mqtt-bot-fe

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'mqtt-bot-fe/package-lock.json'

      - run: npm ci

      - run: npm run build --if-present
